### ISSUE TITLE
indentation level parsing?

### ISSUE THREAD

**Issue by jots** [jasuperior/smpl#6]
could smpl be used to create a simple coffeescript like language based on indentation level?

**Comment by jasuperior** [comment]
hmmmm.... the simple answer is. No.... for now. 

Currently, smpl counts all whitespace as a single character. so, " " & "       " as well as "

" all result in the same single "whitespace" character. 

so:

```
pattern { hello            world } => { console.log("hello world") }
```

and 

```
pattern { hello world } => { console.log("hello world") }
```

are functionally the same.

I can imagine this being a useful feature however. I think the best way to implement this would be to make a couple separate "whitespace" character classes which are strict and count only a single character. So, it could be something like:
- `whitespace` : `[\n\r\t\s]+`
- `newline` : `[\n\r]`
- `space` :  `[ ]+`
- `tab` : `\t+`

this could make it so that you could specifically declare whitespace in your pattern. 

```
pattern { hello $space:space world } => { console.log("hello world") }
hello world //compiles to console.log("hello world")
hello    world /// doesnt compile
hello
world //doesnt compile
```

**Comment by jasuperior** [comment]
@jots  I have added the previously mentioned character classes `newline` `space` and `tab`. I havent merged it to the master branch just now, but if you check out/clone the JaS branch to try it out. 
#7

**Comment by jasuperior** [comment]
I'm closing this issue as per the new merge #7
